help: Exporta base de datos
example:
- (({}.tmp.proc.sig)) --tag drupal10 --lock

task:
  require:
    config:
      - .*(\.local|\.dev|\.test|\.pre|\.stage|\.prod) origin
    opt:
      tag:
        type: String
        default:
      lock:
        type: Boolean
        default: false
  do: 
    - { event: 'origin startup' }
    -
      call: dm.makeDbExport
      args:
        leap_from: (({origin}.appsetting.service.db.leap_from))
        env_key: (({origin}._config_name))
        from_service: (({origin}._tag))-db
        base_image: (({origin}.appsetting.service.db.base_image))
        host: (({origin}.appsetting.service.db.host))
        name: (({origin}.appsetting.service.db.name))
        user: (({origin}.appsetting.service.db.user))
        pass: (({origin}.appsetting.service.db.pass))
        excluded_tables: (({origin}.appsetting.service.db.conf.db-export.excluded-tables))
        backup_db_path: (({origin}.appsetting.path.backup_db))
    - { event: 'origin windup' }