help: Obtiene informaci√≥n
example:
- (({}.tmp.proc.sig))

task:
  require:
    config:
      - .*(\.local|\.dev|\.test|\.pre|\.stage|\.prod) origin
    args:
      type:
        required: false
        type: String
        default:
  do:
    - { event: 'origin startup' }
    -
      call: dm.makeTrace
      args:
        type: (({}.args.type))
    - { event: 'origin windup' }
    
