proxy:
  container_name: ${APPSETTING_SERVICE_PROXY_HOST}
  hostname: ${APPSETTING_SERVICE_PROXY_HOST}
  build:
    context: .
    dockerfile: ./templates/dockerfile/proxy
    args:
      APPSETTING_SERVICE_PROXY_BASE_IMAGE: ${APPSETTING_SERVICE_PROXY_BASE_IMAGE}
  ports:
    - 80:80
    - 8080
    - 443:443
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./templates/dynamic_conf.yaml:/etc/traefik/dynamic_conf.yaml:ro
    - ./templates/traefik.yaml:/etc/traefik/traefik.yaml:ro
    - ./certs:/etc/certs:ro
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.${APPSETTING_SERVICE_PROXY_HOST}.rule=${APPSETTING_PROXY_SERVICE_PROXY_RULE_HOST}"
    - "traefik.http.routers.${APPSETTING_SERVICE_PROXY_HOST}.entrypoints=web"
    - "traefik.port=8080"
  networks:
    - ${COMPOSE_PROJECT_NAME}