next:
  container_name: ${APPSETTING_SERVICE_NEXT_HOST}
  hostname: ${APPSETTING_SERVICE_NEXT_HOST}
  build:
    context: .
    dockerfile: ./templates/dockerfile/next
    args:
      APPSETTING_USER: ${APPSETTING_USER}
      APPSETTING_GID: ${APPSETTING_GID}
      APPSETTING_UID: ${APPSETTING_UID}
      APPSETTING_SERVICE_NEXT_BASE_IMAGE: ${APPSETTING_SERVICE_NEXT_BASE_IMAGE}
  env_file: .env
  working_dir: ${APPSETTING_SERVICE_NEXT_TARGET}
  volumes:
    - 
      consistency: cached
      source: ${APPSETTING_SERVICE_NEXT_SOURCE}
      target: ${APPSETTING_SERVICE_NEXT_TARGET}
      type: bind
  healthcheck:
    interval: 1s
    retries: 120
    start_period: 2m0s
    timeout: 2m0s
  ports: [ "3000:3000" ]