redis:
  container_name: ${APPSETTING_SERVICE_REDIS_HOST}
  hostname: ${APPSETTING_SERVICE_REDIS_HOST}
  build:
    context: .
    dockerfile: ./templates/dockerfile/redis
    args:
      APPSETTING_SERVICE_REDIS_BASE_IMAGE: ${APPSETTING_SERVICE_REDIS_BASE_IMAGE}
  labels:
    - "traefik.http.services.${APPSETTING_SERVICE_REDIS_HOST}.loadbalancer.server.port=6379"
  networks:
    - dmproxy